name: Upload Flare Package

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-flare"

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: flare
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Set Release Version
        shell: bash
        run: TAG="${GITHUB_REF/refs\/tags\/v/}";VERSION="${TAG%-flare}"; echo "RELEASE_VERSION=${VERSION}" >> $GITHUB_ENV
      - name: Build package
        run: python -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: "flare/dist/"
